LaunchActivity (fix): undefined ref to id
An undefined reference to `id` appears to be the cause of the double
click required to open activities. A good reason to fix warnings you can
see in dev mode ....

[Issue: 22]